apiVersion: v1
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-1607455318
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-12-08T19:22:00Z"
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-11.12.1
    component: alertmanager
    heritage: Helm
    release: prometheus-1607455318
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:alertmanager.yml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:component: {}
          f:heritage: {}
          f:release: {}
    manager: Go-http-client
    operation: Update
    time: "2020-12-08T19:22:00Z"
  name: prometheus-1607455318-alertmanager
  namespace: default
  resourceVersion: "19524"
  selfLink: /api/v1/namespaces/default/configmaps/prometheus-1607455318-alertmanager
  uid: 7df75f17-999e-40ba-bba4-50e5c4f32914
