apiVersion: batch/v1
kind: Job
metadata:
  name: job-seed
spec:
  template:
    spec:
      containers:
        - name: mysql-container
          image: nyuappsec/assign3-db:v0
          imagePullPolicy: Never
          command: ["/bin/bash"]
          args: ["-c", "mysql $DBNAME < /seed.sql"]
          env:
            - name: MYSQL_HOST
              value: mysql-service

            - name: MYSQL_USER
              value: root

            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: backend-password
                  key: backend-pass

            - name: DBNAME
              value: GiftcardSiteDB

      restartPolicy: Never
